3 module tasks
js-tasks-ru/jsbasic-20221114_noonecrush pull request #4
Opened 2022-12-10 21:09 UTC by noonecrush

2022-12-10 21:10 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-11 11:36 UTC, SinimaWath requested changes

2022-12-11 11:36 UTC, SinimaWath commented on 3-module/1-task/index.js
> +  return names
`return users.map(element => element.name)`

2022-12-11 11:36 UTC, SinimaWath commented on 3-module/2-task/index.js
> +  });
`return arr.filter(item => item >= a  && item <= b)`

2022-12-11 11:36 UTC, SinimaWath commented on 3-module/4-task/index.js
> +   return mapped.join('\n');
```
return users
  .filter(... => ...)
  .map(...=> ...)
  .join()

```

2022-12-11 14:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-12-11 16:04 UTC, SinimaWath approved these changes

2022-12-11 16:05 UTC, merged